### ISSUE TITLE
Cityscapes dataset training failed. 

### ISSUE THREAD

**Issue by minoTrey** [Lavreniuk/SPIdepth#10]
Hi, thank you for sharing your great work.

I attempted to train the Cityscapes dataset from scratch, but encountered an error. 

I followed your instructions to prepare the dataset. However, when I run train.py, the following error occurs:

  File "/home/pc/anaconda3/envs/SPIdepth/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x5376 and 7168x2048)

It seems that the input and output channels of the first Linear function in self.bins_regressor don't match.

File "depth_decoder_QTR.py", line 49, in forward
y = self.bins_regressor(summarys.view(bs, Q*E))

Could you provide guidance on how to resolve this issue?

Thank you in advance!

**Comment by Lavreniuk** [comment]
Hi @minoTrey, thanks for your interest in the model!

I recommend checking out [this file](https://github.com/Lavreniuk/SPIdepth/blob/main/args_files/args_cvnXt_H_cityscapes_finetune_eval.txt) to ensure all your parameters are correctly set. If you're looking to train the H version from scratch, you can use the ./args_files/hisfog/kitti/cvnXt_H_320x1024.txt file as a starting point, and just adjust the dataset paths accordingly.

**Comment by minoTrey** [comment]
It works! Thank you very much.

By the way, I wonder how the GT Depth of the Cityscapes dataset was generated. Is it the same as the data in disparity_sequence_trainvaltest.zip?

Thank you in advance!

**Comment by minoTrey** [comment]
Thank you very much!

**Comment by Lavreniuk** [comment]
I'm happy to assist! If you find the model useful, I would really appreciate it if you could give our GitHub repo an upvote.

**Comment by Lavreniuk** [comment]
@minoTrey, I'm happy to assist! If you find the model useful, I would really appreciate it if you could give our GitHub repo an upvote.
