### ISSUE TITLE
eigen_zhou/train_files.txt

### ISSUE THREAD

**Issue by PoKoHA** [Lavreniuk/SPIdepth#2]
Hello.

In the autho's paper, it's stated as 26K images, but in reality, there are about 71K data names written in egien_zhou/train_files.txt.

For reproduction purposes, what is the number of data samples used in the kitti_egien split?

Thank you.

**Comment by Lavreniuk** [comment]
hi, @PoKoHA , thank you for your interest in our model.
I followed the same settings as the SQLdepth paper. For the KITTI Eigen split, approximately 70k images were used during the unsupervised pretraining phase, where depth maps were not employed. However, for training the model with depth maps, only around 22k images were used.

For more details, you can refer to the exact file used for training: [KITTI Eigen training files](https://raw.githubusercontent.com/Lavreniuk/SPIdepth/main/finetune/train_test_inputs/kitti_eigen_train_files_with_gt.txt) or refer to discussion of this question earlier https://github.com/hisfog/SfMNeXt-Impl/issues/26.
