### ISSUE TITLE
RuntimeError: Unknown model (convnextv2_huge.fcmae_ft_in22k_in1k_384)

### ISSUE THREAD

**Issue by SuteraBlu** [Lavreniuk/SPIdepth#7]
I am trying to run inference with my own image using the provided code as shown:
Can someone explain the following error to me please:

![Screenshot from 2024-10-14 09-13-26](https://github.com/user-attachments/assets/e3f53765-c59a-4c19-a70a-859646f1dbf4)

**Comment by hnjj23** [comment]
@SuteraBlu, thank you for your interest in our model! It appears that you are using an outdated version of the timm library. Please update to the latest version or one of the more recent versions.

**Comment by Lavreniuk** [comment]
@SuteraBlu, thank you for your interest in our model! It appears that you are using an outdated version of the timm library. Please update to the latest version or one of the more recent versions.

**Comment by SuteraBlu** [comment]
Yes that's exactly the reason! Thank you!
